import { posts } from "#site/content";
import { PostItem } from "@/components/post-item";
import { QueryPagination } from "@/components/query-pagination";
import { sortPosts } from "@/lib/utils";
import { Metadata } from "next";



export const metadata: Metadata = {
title: "My Learning App",
description: "Generated by create next app"
}
const POST_PER_PAGE = 5;

interface BlogPageProps {
  searchParams: {
    page?: string;
  };
}

export default async function BlogPage({ searchParams }: BlogPageProps) {
  const currentPage = Number(searchParams?.page) || 1
  const sortedPosts = sortPosts(posts.filter((post) => post.published));
  const totalPages = Math.ceil(sortedPosts.length / POST_PER_PAGE);


  const displayPosts = sortedPosts.slice(
    POST_PER_PAGE * (currentPage - 1),
    POST_PER_PAGE * currentPage
  )

  return (
    <div className="container max-w-4xl py-6 lg:py-10">
      <div className="flex-1 space-y-4">
        <h1 className=" inline-block font-black text-4xl lg:text-5xl">Blog</h1>
        <p className="text-xl text-muted-foreground">
          this is blog pages.
        </p>
      </div>
      <hr className="mt-8" />
      {displayPosts?.length > 0 ? (<ul className="flex flex-col">

        {displayPosts.map((post) => {
          const { slug, date, title, description } = post
          return (
            <li key={slug}>
              <PostItem slug={slug} date={date} title={title} description={description} />
            </li>
          )
        })}
      </ul>
      ) : (
        <p>Nothing is here yet!</p>
      )}
      <QueryPagination totalPages={totalPages} className=" justify-end mt-4" />
    </div>
  )
}